# Generated by Django 6.0.5 on 2026-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_salaire_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gain_salaire_bonus_note', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gain_salaire_emprunts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('filiere_cible', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='livres/pdfs/')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='livres/couvertures/')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('nombre_pages', models.PositiveIntegerField(default=0)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('reserve', 'Réservé'), ('archive', 'Archivé')], default='disponible', max_length=20)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('musique_ambiance', models.FileField(blank=True, help_text="Fichier audio (MP3) pour la musique d'ambiance du livre", null=True, upload_to='livres/musiques/')),
                ('max_emprunts_simultanes', models.PositiveIntegerField(default=1)),
                ('nombre_emprunts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
