# Generated by Django 6.0.5 on 2026-06-07 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='books.categorie'),
        ),
        migrations.AddField(
            model_name='livre',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_ajoutes_par', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='bibliothecaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_ajoutes_bibliothecaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='livres', to='books.categorie'),
        ),
        migrations.AddField(
            model_name='livre',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='books.livre'),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.livre'),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernote',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.livre'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userword',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='books.livre'),
        ),
        migrations.AddField(
            model_name='userword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('livre', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together={('user', 'livre')},
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'livre')},
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'livre', 'word')},
        ),
    ]
