# Generated by Django 6.0.5 on 2026-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=500.0, help_text='Solde disponible en dirhams (DH)', max_digits=10)),
                ('numero_carte', models.CharField(blank=True, help_text='Numéro de carte bancaire (16 chiffres)', max_length=16, null=True)),
                ('date_expiration', models.CharField(blank=True, help_text='Format MM/YY', max_length=5, null=True)),
                ('cryptogramme', models.CharField(blank=True, help_text='CVV/CVC (3 chiffres)', max_length=3, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompteEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='BiblIntel - Compte principal', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte entreprise',
                'verbose_name_plural': 'Comptes entreprise',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('paiement_amende', "Paiement d'amende"), ('rechargement', 'Rechargement du compte'), ('remboursement', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
