# Generated by Django 6.0.5 on 2026-06-07 17:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('bibliothecaire', 'Bibliothécaire'), ('personne', 'Personne normale'), ('employeur', 'Employeur'), ('admin', 'Administrateur')], default='personne', max_length=20)),
                ('filiere', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('points_fidelite', models.PositiveIntegerField(default=0)),
                ('est_blackliste', models.BooleanField(default=False)),
                ('date_blacklist', models.DateTimeField(blank=True, null=True)),
                ('raison_blacklist', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('salaire_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rib', models.CharField(blank=True, help_text='RIB pour virement salaire', max_length=50, null=True)),
                ('domaine_professionnel', models.CharField(blank=True, max_length=100, null=True)),
                ('matiere_enseignee', models.CharField(blank=True, max_length=100, null=True)),
                ('est_valide', models.BooleanField(default=False, help_text="Compte validé par l'admin", null=True)),
                ('date_demande_validation', models.DateTimeField(blank=True, null=True)),
                ('categories_preferees', models.ManyToManyField(blank=True, to='books.categorie')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='biblintel_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='biblintel_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
