# Generated by Django 6.0.5 on 2026-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('crud_livre', 'CRUD Livre'), ('crud_user', 'CRUD Utilisateur'), ('emprunt', 'Emprunt'), ('retour', 'Retour'), ('blacklist', 'Blacklist'), ('reservation', 'Réservation'), ('paiement', 'Paiement')], max_length=20)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('temps_utilisation', models.IntegerField(default=0)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
