# Generated by Django 6.0.5 on 2026-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('retour_proche', 'Retour proche'), ('retard', 'Retard'), ('validation', 'Validation emprunt'), ('refus', 'Refus emprunt'), ('disponible', 'Livre disponible'), ('blacklist', 'Blacklist'), ('paiement_manuel', 'Paiement manuel')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
