# Generated by Django 6.0.5 on 2026-06-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('position_file', models.PositiveIntegerField(default=1)),
                ('est_active', models.BooleanField(default=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('en_cours', 'En cours'), ('retourne', 'Retourné'), ('retard', 'En retard'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('position_file', models.PositiveIntegerField(default=0)),
                ('a_prolonge', models.BooleanField(default=False)),
                ('nombre_prolongations', models.PositiveSmallIntegerField(default=0)),
                ('amende_totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('est_payee', models.BooleanField(default=False)),
                ('derniere_page_lue', models.IntegerField(blank=True, null=True)),
                ('demande_paiement_manuel', models.BooleanField(default=False)),
                ('paiement_valide_le', models.DateTimeField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='books.livre')),
            ],
        ),
    ]
