# Generated by Django 6.0.5 on 2026-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("auteur", models.CharField(max_length=255)),
                ("resume", models.TextField()),
                (
                    "filiere_cible",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fichier_pdf", models.FileField(upload_to="livres/pdfs/")),
                ("couverture", models.ImageField(upload_to="livres/couvertures/")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Mots-clés séparés par des virgules",
                        max_length=500,
                    ),
                ),
                ("nombre_pages", models.PositiveIntegerField(default=0)),
                ("langue", models.CharField(default="Français", max_length=50)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("emprunte", "Emprunté"),
                            ("reserve", "Réservé"),
                            ("archive", "Archivé"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("nombre_emprunts", models.PositiveIntegerField(default=0)),
                (
                    "note_moyenne",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
            ],
            options={
                "ordering": ["-date_ajout"],
            },
        ),
    ]
