# Generated by Django 6.0.5 on 2026-05-13 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="avis",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="categorie",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sous_categories",
                to="books.categorie",
            ),
        ),
        migrations.AddField(
            model_name="livre",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres",
                to="books.categorie",
            ),
        ),
        migrations.AddField(
            model_name="avis",
            name="livre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avis",
                to="books.livre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avis",
            unique_together={("livre", "utilisateur")},
        ),
    ]
