# Generated by Django 4.2.30 on 2026-05-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="couverture",
            field=models.ImageField(
                blank=True, null=True, upload_to="livres/couvertures/"
            ),
        ),
        migrations.AlterField(
            model_name="livre",
            name="fichier_pdf",
            field=models.FileField(blank=True, null=True, upload_to="livres/pdfs/"),
        ),
    ]
