# Generated by Django 4.2.30 on 2026-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_livre_couverture_alter_livre_fichier_pdf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avis",
            options={"verbose_name": "Avis", "verbose_name_plural": "Avis"},
        ),
        migrations.AlterModelOptions(
            name="categorie",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="livre",
            options={
                "ordering": ["-date_ajout"],
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
            },
        ),
        migrations.AlterField(
            model_name="categorie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
